# Generated by Django 4.0.4 on 2022-07-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_channel',
            name='channel_subject',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
