# Generated by Django 4.0.4 on 2022-07-18 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_public_channel_channel_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_channel',
            name='channel_members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
