# Generated by Django 4.0.4 on 2022-07-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_public_posts_post_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_channel',
            name='channel_date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
