# Generated by Django 4.0.4 on 2022-07-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_public_channel_channel_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_posts',
            name='downvotes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='public_posts',
            name='upvotes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
